# Generated by Django 4.0.3 on 2022-03-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.TextField(default=None, null=True),
        ),
    ]
